server:
  port: 8999 #项目端口

spring:
  application:
    name: yog-web
  profiles:
      active: dev

dubbo:
  application:
    name: yog-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880

