server:
  port: 8099 #项目端口

spring:
  application:
    name: yog-web
  profiles:
      active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: consumer-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
  scan:
    base-packages: com.bruce.consumer.controller
  qos:
    port: 22223
  consumer:
    check: false