server:
  port: 8088 #项目端口

spring:
  application:
    name: yog-service #项目名称
  profiles:
    active: dev
  cloud:
    nacos: # nacos配置
      config:
        server-addr: 127.0.0.1:8848 # nacos地址和端口

dubbo: # dubbo配置
  application:
    name: provider-server # dubbo服务名称
  protocol:
    port: 20880 # dubbo服务端口
    name: dubbo # dubbo服务协议名称
  registry: # dubbo使用的注册中心
    address: nacos://10.10.8.165:8848 # dubbo注册中心地址
  monitor:
    protocol: registry
  scan:
    base-packages: com.bruce.provider.service
